on:
  push:
    branch:
      - master
name: ci
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Build
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: docker.pkg.github.com/phpdocumentor/coding-standard/phpcs
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com

      - name: self-run
        uses: ./
        with:
          args: "-i"
